### ISSUE TITLE
Лучше возвращать строку для сообщения о результате выполнения

### ISSUE THREAD

**Issue by IndianMax03** [DarkoKoroleva/Pokenoms#6]
https://github.com/DarkoKoroleva/Pokenoms/blob/b5608183b63524fd9c0f9fb215892e52cd619c52/ConsolApp/src/Command.java#L2

**Comment by DarkoKoroleva** [comment]
почему строку? может лучше boolean

**Comment by IndianMax03** [comment]
Потому что эту строку можно будет отдать клиенту и она более говорящая, чем true/false. Идеальный вариант создать класс Response, в котором можно держать и сообщение об ошибке, и результат выполнения, и прочие поля (в т.ч. эксепшен, который можно отложенно выкинуть). Короче пофантазируй, но Boolean -- это слишком мало.
